### ISSUE TITLE
Error accepting invitation (staging)

### ISSUE THREAD

**Issue by fancyremarker** [aptible/dashboard.aptible.com#507]
Error 1:

```
Started POST "/verifications" for 104.218.141.34 at 2016-01-18 15:09:15 +0000
Processing by VerificationsController#create as HTML
  Parameters: {"verification_code"=>"[FILTERED]", "invitation_id"=>nil, "type"=>"email", "user_id"=>nil, "reset_code"=>nil, "password"=>"[FILTERED]"}
Completed 500 Internal Server Error in 198ms (ActiveRecord: 49.2ms)

NoMethodError (undefined method `organization' for nil:NilClass):
  app/services/verifications/user.rb:20:in `save!'
  app/controllers/verifications_controller.rb:11:in `create'
```

Error 2: `Type Error` / `undefined. Maybe the URL you visited is no longer valid?` in Dashboard

**Comment by fancyremarker** [comment]
Client error from Error 2:

```
Error while processing route: welcome.first-app Cannot read property 'get' of undefined TypeError: Cannot read property 'get' of undefined
```

**Comment by krallin** [comment]
(more on the client error)

```
Error while processing route: welcome.first-app Cannot read property 'get' of undefined TypeError: Cannot read property 'get' of undefined
    at https://dashboard.aptible-staging.com/assets/diesel-bca8220056a5f72c1a9f2536efb52822.js:30:12750
    at b (https://dashboard.aptible-staging.com/assets/vendor-ce2f9c6237e9aa8ae3f6b760a268a6fa.js:21:2822)
    at y (https://dashboard.aptible-staging.com/assets/vendor-ce2f9c6237e9aa8ae3f6b760a268a6fa.js:21:2917)
    at g (https://dashboard.aptible-staging.com/assets/vendor-ce2f9c6237e9aa8ae3f6b760a268a6fa.js:21:2725)
    at https://dashboard.aptible-staging.com/assets/vendor-ce2f9c6237e9aa8ae3f6b760a268a6fa.js:14:5430
    at r.invokeWithOnError (https://dashboard.aptible-staging.com/assets/vendor-ce2f9c6237e9aa8ae3f6b760a268a6fa.js:4:16337)
    at Object.r.flush (https://dashboard.aptible-staging.com/assets/vendor-ce2f9c6237e9aa8ae3f6b760a268a6fa.js:4:16789)
    at Object.n.flush (https://dashboard.aptible-staging.com/assets/vendor-ce2f9c6237e9aa8ae3f6b760a268a6fa.js:4:14832)
    at Object.a.end (https://dashboard.aptible-staging.com/assets/vendor-ce2f9c6237e9aa8ae3f6b760a268a6fa.js:4:7962)
    at Object.a.run (https://dashboard.aptible-staging.com/assets/vendor-ce2f9c6237e9aa8ae3f6b760a268a6fa.js:4:9043)
```
